
[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 8
y = 8

[general]
live_config_reload = true

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]
